site_name: Medplexity
site_url: https://medplexity.readthedocs.io/en/latest/
repo_url: https://github.com/MaksymPetyak/medplexity
site_description: Medplexity is a python library to help with evaluation of LLMs for medical applications.
site_author: Maksym Petyak

theme:
  name: material
  highlightjs: true

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Key concepts: key-concepts.md
  - Benchmarks:
      - benchmarks/medqa.md
      - benchmarks/medmcqa.md
      - benchmarks/mmlu.md
      - benchmarks/pubmedqa.md
      - benchmarks/healthsearchqa.md
      - benchmarks/medicationqa.md
  - License: license.md
#- Release Notes: release-notes.md
#- Contributing: CONTRIBUTING.md
extra:
  version: "0.1.0"
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
#        python:
#          options:
#            docstring_style: google
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
